### ISSUE TITLE
Grunt devbuild fails on sass task

### ISSUE THREAD

**Issue by jfaron** [crackernutter/calcite-dojo-build-template#1]
The following error occurs which prevents devbuild from running: 
"Running "sass:expanded" (sass) task"
>> Error: File to import not found or unreadable: bootstrap/mixins
>>        Parent style sheet: C:/inetpub/aaProjects/calcite-dojo-build-template/
calcite-dojo-build-template/node_modules/calcite-maps/lib/sass/bootstrap-components.scss
>>         on line 10 of node_modules/calcite-maps/lib/sass/bootstrap-components.scss
>> >> @import "bootstrap/mixins";

The problem is in the include Paths, line 21 of gruntfile.js, which needs to change from './node_modules/calcite-bootstrap/node_modules/bootstrap-sass/assets/stylesheets'  to './node_modules/bootstrap-sass/assets/stylesheets'
Then, all works as expected!

**Comment by crackernutter** [comment]
Thanks for the info!  However, my bootstrap-sass asset is not at the root of my node_modules directory.  It's located within calcite-bootstrap's node_modules directory, which is why my grunt task uses that location.  If I make the change you suggested, then my grunt task fails.  Is bootstrap-sass in the root of your node_modules directory?

**Comment by jfaron** [comment]
Yes. When I originally ran npm install, there was not a node_modules directory created within Calcite-Bootstrap. Bootstrap-sass was created in the root of node_modules. I thought that the problem might be related to version, so I deleted it and added/installed the latest version of Bootstrap-sass as a dependency in package.json, but that had no effect. It was then that I discovered the include path variance. 

I wonder why you have a different experience with npm install than I do with the calcite-bootstrap in node_modules? I am using Windows, so perhaps it installs differently on a mac (assuming you use a mac)?


Date: Wed, 29 Jun 2016 08:15:43 -0700

**Comment by crackernutter** [comment]
Interesting.  Certainly your path is the one listed in Esri's documentation.  I changed my path when I bumped up against an error that it couldn't find bootstrap-sass at the root of my node_modules.  I'm not too familiar with npm, but there might be a global setting that switches how dependencies are installed.  Mine might be set to nested (so therefore inside calcite-bootstrap), whereas yours is set to flat (therefore at the root of node_modules).  That's the only thing I can think of....

**Comment by jfaron** [comment]
Anyhow, thanks for following up, and for releasing the repo. I'm planning on checking it out in correlation with an application that I'm porting over from flex. I like the look of Calcite maps. I just have to configure a side panel to work on mobile in a manner similar to how  shortlist story maps works, and I hopefully will be good to go.

Date: Thu, 30 Jun 2016 13:12:00 -0700
